[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "trains"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "bidict>=0.23.1",
    "networkx>=3.5",
    "pydantic>=2.12.5",
    "torch",
    "torch-geometric>=2.7.0",
]

